image: Visual Studio 2015
clone_depth: 5
platform: Any CPU
configuration: Release

environment:
  email:
    secure: fQLSZSBDhJn9IuY6H5Tr964ilnvnGdeldMhv5I2vpqE=
  githubToken:
    secure: K71ovddtT7BuOR1D1K9uVRdOT2+Apl6GdQjBYjUki/ySUX9EcWb2MNtupx5ymrkt
  nugetToken:
    secure: LKL3BM5Iphp+fjoZzhqLAMrQOLrNXvY4tEEa5zRKpTY2Ti4gOzBUhxaprnCzfTO3

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.5.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
build:
  parallel: true
  project: .\DryIoc.Wcf.sln
  verbosity: detailed
  
test_script:
    - ps: .\run-tests.ps1

cache:
  - packages -> **\packages.config

before_deploy:
  - ps: .\nuget\pack.ps1
  
deploy:
  description: 'Release'
  - provider: GitHub
      auth_token: %githubToken%
      artifact:
        - path: .\nuget\artifacts\*.nupkg
      on:
        branch: master                 # release from master branch only
        appveyor_repo_tag: true 
  - provider: NuGet
    api_key: %nugetToken%
    skip_symbols: false
    artifact:
      - path: .\nuget\artifacts\*.nupkg
    on:
      appveyor_repo_tag: true

      notifications:

  # Email
- provider: Email
  to:
    - %email%
    subject: 'Build {{status}}' 
    message: "{{message}}, {{commitId}}"
    on_build_status_changed: true