image: Visual Studio 2015
clone_depth: 5
platform: Any CPU
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.5.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - cmd: nuget restore -verbosity detailed

build:
  parallel: true
  project: .\DryIoc.Wcf.sln
  verbosity: detailed
  
test_script:
    - ps: .\run-tests.ps1

#cache:
#  - packages -> **\packages.config

before_deploy:
  - ps: .\nuget\pack.ps1
  
deploy:
  - provider: NuGet
    api_key:
      secure: LKL3BM5Iphp+fjoZzhqLAMrQOLrNXvY4tEEa5zRKpTY2Ti4gOzBUhxaprnCzfTO3
    skip_symbols: false
    artifact: '.\nuget\artifacts\*.nupkg'
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Release'
    release: DryIoc.Wcf.dll-v$(appveyor_build_version)
    auth_token:
      secure: K71ovddtT7BuOR1D1K9uVRdOT2+Apl6GdQjBYjUki/ySUX9EcWb2MNtupx5ymrkt
    artifact: '.\nuget\artifacts\*.nupkg'
    on:
      appveyor_repo_tag: true 